#!/bin/zsh

# copy tmux config
cp -r ./tmux/tmux/plguins/ ~/.config/tmux/
echo "Copied 'plugins' directory to ~/.config/tmux/"
cp ./tmux/tmux/tmux.conf ~/.config/tmux/
echo "Copied 'tmux.conf' file to ~/.config/tmux/"
cp -r ./tmux/.tmux ~/.tmux
echo "Copied '.tmux' directory to ~/.tmux"

